services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      - WEBPASSWORD=ChangeM3Pls!!
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
      - ./certs:/etc/certs
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      dns_underrouting:
        ipv4_address: 192.168.0.232

  adguardhome:
    image: adguard/adguardhome
    ports:
      - "5333:53/tcp"
      - "5333:53/udp"
      - "3000:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "784:784/udp"
      - "8853:8853/udp"
    volumes:
      - ./AdGuardHome:/opt/AdGuardHome
    restart: unless-stopped
    depends_on:
      - pihole
    networks:
      dns_underrouting:
        ipv4_address: 192.168.0.242

  unbound:
    image: plooshdns/unbound
    build:
      context: ../unbound-docker
      dockerfile: ../unbound-docker/Dockerfile
    container_name: unbound
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    networks:
      dns_underrouting:
        ipv4_address: 192.168.0.222


networks:
  dns_underrouting:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
